### ISSUE TITLE
disable english rules in a german document

### ISSUE THREAD

**Issue by arantxax** [ltex-plus/lsp-cli-plus#21]
I'm working currently in a project with LaTeX with following files:

1. Main
2. Kapitel 1
3. Kapitel 2, etc.

They have a mixture of english and german. (But mainly german!). By running the ltex+ it only proofs against englisch rules.

I couldn't reproduce a minimal working example, but I selected only the relevant information regarding languages. 
In Main I have:
```
% Anpassung an Landessprache ---------------------------------------------------
\usepackage[ngerman]{babel}
% Umlaute ----------------------------------------------------------------------
\usepackage[T1]{fontenc}
\documentclass[
	ngerman,
	numbers=noendperiod
]{scrartcl}
\usepackage[utf8]{inputenc} % muss als erstes eingebunden werden, da Meta/Packages ggfs. Sonderzeichen enthalten`

\begin{document}
\selectlanguage{ngerman}  % Explicitly tell LaTeX to use German
Mischung von Sprachen: Deutsch (ok) und ein bisschen english.
\input{Kapitel1}
\input{Kapitel2}
\end{document}
```

Inside TeXworks IDE I call the following batch file:
`ltex+/ltex-ls-plus-18.2.0/bin/ltex-cli-plus.bat`

With following arguments (for path and additional):
`absolute_path_working_folder/`
`--client-configuration=relative_path_to_ltex/bin/.lsp-cli.json`
`--verbose`

I'm using ltex-ls-plus-18.2.0.
JSON-FILE:
`{
  "programName": "ltex-cli-plus",
  "helpMessage": {
    "description": "LTeX CLI - Command-line interface for LTeX LS",
    "visibleArguments": [
      "--client-configuration",
      "--verbose"
    ]
  },
  "defaultValues": {
    "--hide-commands": true,
    "--server-command-line": "ltex-ls-plus.bat"
  },
  "client": {
    "configuration": {
      "ltex": {
        "language": "de-DE",
	"documentLanguages": ["de-DE"],
 	"disabledRules": [
          "MORFOLOGIK_RULE_EN_US"
        ],
        "enabledRules": ["MORFOLOGIK_RULE_DE_DE"]
      }
    }
  }
}`

**Comment by spitzerd** [comment]
I just tried your example and LTeX+ highlights `english` as spelling mistake. The underlying rule is `[GERMAN_SPELLER_RULE]`. So you would have to disable the rule `[GERMAN_SPELLER_RULE]` and not `[MORFOLOGIK_RULE_EN_US]`

**Comment by arantxax** [comment]
Thanks @spitzerd,

I rather not disable the rule [GERMAN_SPELLER_RULE], because I can misspell in german. But! I found a turnaround reading the documentation and forums.

Main is the same, just adding:
```
\begin{document}
\selectlanguage{ngerman}  % Explicitly tell LaTeX to use German

Dankeschön für Ihre Rückmldung. %Some mispell here
\input{Kapitel1}
\end{document}
```

And the Kapitel1:

```
\selectlanguage{ngerman}  % Explicitly tell LaTeX to use German

Dankeschön für Ihr \foreignlanguage{english}{Feedback}.
```


And the JSON is the simpler as it can be, no setting at all:
`{ "programName": "ltex-cli-plus", "helpMessage": { "description": "LTeX CLI - Command-line interface for LTeX LS", "visibleArguments": [ "--client-configuration", "--verbose" ] }, "defaultValues": { "--hide-commands": true, "--server-command-line": "ltex-ls-plus.bat" } }`

It fits me and I hope it helps others for multilingual documents 👍
